numpy기초

In [1]:
import numpy as np

In [5]:
a1=np.array([1,2,3])
print('a1 type:',type(a1))
print('a1 shape:',a1.shape)

a2=np.array([[1,2,3],[4,5,6]])
print('a2 type:',type(a2))
print('a2 shape:',a2.shape)

a3=np.array([[1,2,3]])
print('a3 type:',type(a3))
print('a3 shape:',a3.shape)

a1 type: <class 'numpy.ndarray'>
a1 shape: (3,)
a2 type: <class 'numpy.ndarray'>
a2 shape: (2, 3)
a3 type: <class 'numpy.ndarray'>
a3 shape: (1, 3)


In [13]:
print(f'a1 {a1.ndim}차원 a2 {a2.ndim}차원 a3 {a3.ndim}차원')

a1 1차원 a2 2차원 a3 2차원


In [18]:
#ndarray의 데이터 타입

list1=[1,2,3]
print(type(list1))
a1=np.array(list1)
print(type(a1))
print(a1,a1.dtype)



<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int32


In [20]:
list2=[1,2,'test']
print(type(list2))
a2=np.array(list2)
print(type(a2))
print(a2,a2.dtype)

list3=[1,2,3.0]
print(type(list3))
a3=np.array(list3)
print(type(a3))
print(a3,a3.dtype)

<class 'list'>
<class 'numpy.ndarray'>
['1' '2' 'test'] <U11
<class 'list'>
<class 'numpy.ndarray'>
[1. 2. 3.] float64


In [24]:
#astype 메서드

a_int=np.array([1,2,3])
a_float=a_int.astype('float64')
print(a_float,a_float.dtype)

a_int1=a_float.astype('int32')
print(a_int1,a_int1.dtype)

a_float1=np.array([1.1,2.1,3.1])
a_int2=a_float1.astype('int32')
print(a_int2,a_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


In [26]:
#ndarray 편리하게 생성하기 

seq_array=np.arange(10)
print(seq_array)
print(seq_array.shape)

[0 1 2 3 4 5 6 7 8 9]
(10,)


In [32]:
zero_array=np.zeros((3,2),dtype='int32')
print(zero_array)
print(zero_array.shape)

one_array=np.ones((3,2))
print(one_array)
print(one_array.shape)

[[0 0]
 [0 0]
 [0 0]]
(3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
(3, 2)


reshape

In [36]:
a1=np.arange(10)
print('a1:\n',a1)

a2=a1.reshape(2,5)
print('a2:\n',a2)

a3=a1.reshape(5,2)
print('a3:\n',a3)

a1:
 [0 1 2 3 4 5 6 7 8 9]
a2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
a3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [38]:
#-1 인자를 사용하면 편리하다

a1=np.arange(10)
print(a1)

a2=a1.reshape(-1,5)
print(a2.shape)

a3=a1.reshape(5,-1)
print(a3.shape)

[0 1 2 3 4 5 6 7 8 9]
(2, 5)
(5, 2)


In [49]:
#-1 인자는 reshape(-1,1) 형태로 자주 사용된다. 
# 어떤 형태던 2차원의 반드시 1개의 열을 가지는 ndarray로 반환됨을 의미
#tolist 메서드로 리스트 자료형으로 변환이 가능하다.

a1=np.arange(8)
a1_3d=a1.reshape(2,2,2)
print('a1:\n',a1_3d.tolist())

#3차원 array를 2차원 array로 변환
a2=a1_3d.reshape(-1,1)
print('a2:\n',a2.tolist())
print(a2.shape)

#1차원 array를 2차원 array로 변환
a3=a1.reshape(-1,1)
print('a3:\n',a3.tolist())
print(a3.shape)

a1:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
a2:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
(8, 1)
a3:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
(8, 1)


데이터 세트 선택하기 - 인덱싱

In [50]:
#단일 값 추출
a1=np.arange(1,10)
print('a1:\n',a1)

a1:
 [1 2 3 4 5 6 7 8 9]


In [51]:
value=a1[2]
print(value)

3


In [59]:
a1=np.arange(1,10)
a2=a1.reshape(3,3)
print('a2:\n',a2,'\n')

print(f'(0,0): {a2[0,0]}')
print(f'(0,1): {a2[0,1]}')
print(f'(1,0): {a2[1,0]}')
print(f'(2,2): {a2[2,2]}')

a2:
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 

(0,0): 1
(0,1): 2
(1,0): 4
(2,2): 9


In [65]:
#팬시 인덱싱

a1=np.arange(1,10)
a2=a1.reshape(3,3)

a3=a2[[0,1],2]
print(f'a2[[0,1],2] -> {a3.tolist()}\n')

a4=a2[[0,1],0:2]
print(f'a2[[0,1],0:2] -> {a4.tolist()}\n')

a5=a2[[0,1]]
print(f'a2[[0,1]] -> {a5.tolist()}')

a2[[0,1],2] -> [3, 6]

a2[[0,1],0:2] -> [[1, 2], [4, 5]]

a2[[0,1]] -> [[1, 2, 3], [4, 5, 6]]


In [66]:
#불린 인덱싱

a1=np.arange(1,10)
a2=a1[a1>5]
print('a2\n',a2)

a2
 [6 7 8 9]


In [68]:
a1>5

array([False, False, False, False, False,  True,  True,  True,  True])

In [70]:
index=np.array([5,6,7,8])
a3=a1[index]
print('a3\n',a3)

a3
 [6 7 8 9]


행렬의 정렬

In [78]:
#sort(), argsort()

a1=np.array([3,1,9,5])


sort_a1=np.sort(a1)
print(sort_a1,'\n')

sort_a1_desc=np.sort(a1)[::-1]
print('desc:',sort_a1_desc,'\n')

#a1.sort()는 반환값은 None, 기존 array인 a1을 정렬해서 저장
sort_a1_2=a1.sort()
print(sort_a1_2,'\n')
print(a1)

[1 3 5 9] 

desc: [9 5 3 1] 

None 

[1 3 5 9]


In [82]:
#2차원 이상 정렬

a1=np.array([[8,12],
             [7,1]])

sort_a1=np.sort(a1,axis=0) #행 방향 정렬
print('sort_a1_axis=0\n',sort_a1,'\n')

sort_a1_2=np.sort(a1,axis=1) #열 방향 정렬
print('sort_a1_axis=1\n',sort_a1_2)

sort_a1_axis=0
 [[ 7  1]
 [ 8 12]] 

sort_a1_axis=1
 [[ 8 12]
 [ 1  7]]
